title: "aabccd021's blog"

email: aabccd021@gmail.com
desc: "This is Minima, an undoubtedly simple and lightweight dark/light mode theme for Hexo. I created this from scratch using Skeleton CSS boilerplate. It only uses CSS and Vanilla JS, without using unnecessary third-party 'render-blocking' libraries! ğŸ˜"

# social profile at the footer/bottom
footer: true

# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true
